# Generated by Django 4.0.4 on 2022-05-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bio',
            new_name='new_bio',
        ),
    ]
