# Generated by Django 4.0.4 on 2022-05-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_rename_bio_player_new_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='new_bio',
            new_name='bio',
        ),
    ]
