# Generated by Django 4.0.4 on 2022-05-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0004_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='game_category',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='game_image',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='game_image',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='player_id',
            new_name='player',
        ),
    ]
