# Generated by Django 4.0.4 on 2022-05-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0006_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='review',
            field=models.ManyToManyField(through='raterprojectapi.Review', to='raterprojectapi.player'),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='raterprojectapi.game'),
        ),
    ]
