# Generated by Django 4.0.4 on 2022-05-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0007_game_review_alter_review_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='review',
        ),
    ]
